export class PreferenceConstant {
  static readonly USER_TOKEN_KEY = 'user_token'
  static readonly IS_FIRST_OPEN_KEY = 'isFirstOpen';
  static readonly IS_AUTOLOGIN_OPEN_KEY = 'isAutoLogin';
  static readonly LAST_LOGIN_EMAIL_KEY = 'lastLoginEmail';
  static readonly LAST_LOGIN_PASSWORD_KEY = 'lastLoginPassword';
  static readonly CART_KEY = 'cart';
  static readonly CART_ISCHOOSE_KEY = 'cart_ischoose';
  static readonly USER_DATA = 'user_data';
  static readonly  ORDER_LIST_KEY = 'order_list';
  static readonly  POST_LIST = 'post_list';
}