export class RouterNameConstants {
  static readonly PHONE_INDEX: string = 'phone_index';
}

export class BuilderNameConstants {
  static readonly LOGIN_LOGINPAGE: string = 'login_loginPage';
  static readonly LOGIN_SGINPAGE: string = 'login_sginPage';
  static readonly TAB_TABPAGE: string = 'tab_tabpage';
  static readonly MINE_MINEPAGE: string = 'mine_minepage';
  static readonly MINE_USERINFORMATION: string = 'mine_userinformation';
}