export class RouterNameConstants {
  static readonly PHONE_INDEX: string = 'phone_index';
  static readonly TABPAGE: string = 'tab_tabpage';
}

export class BuilderNameConstants {
  static readonly LOGIN_LOGINPAGE: string = 'login_loginPage';
  static readonly LOGIN_SGINPAGE: string = 'login_sginPage';
  static readonly TAB_TABPAGE: string = 'tab_tabpage';
  static readonly MINE_MINEPAGE: string = 'mine_minepage';
  static readonly MINE_USERINFORMATION: string = 'mine_userinformation';
  static readonly MINE_NAMECHANGE: string = 'mine_namechange';
  static readonly MINE_EMAILCHANGE: string = 'mine_emailchange';
  static readonly SHOPCAR_PRODUCTINFOPAGE: string = 'shopcar_productinfopage';
  static readonly SHOPCAR_PRODUCTAPPRAISEPAGE: string = 'shopcar_productappraisepage';
  static readonly HOME_SHOPINFOPAGE: string = 'home_shopinfopage';
}