/**
 * 登录界面需要的资源
 */
export class ResourceConstants {
  static readonly ACCOUNT_SHOW_UP: Resource = $r("app.media.account_show_up")
  static readonly ACCOUNT_SHOW_DOWN: Resource = $r("app.media.account_show_down")
  static readonly USER_TOKEN_KEY = 'user_token'
  static readonly IS_FIRST_OPEN_KEY = 'isFirstOpen';
  static readonly IS_AUTOLOGIN_OPEN_KEY = 'isAutoLogin';
  static readonly  LAST_LOGIN_EMAIL_KEY = 'lastLoginEmail';
  static readonly LAST_LOGIN_PASSWORD_KEY = 'lastLoginPassword'
}